// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbhqQmnAD3fcA3UYsKxK03SJyimNDTf8k',
    appId: '1:144488728010:web:1fccdff955274c8a63bb33',
    messagingSenderId: '144488728010',
    projectId: 'najiztest',
    authDomain: 'najiztest.firebaseapp.com',
    storageBucket: 'najiztest.appspot.com',
    measurementId: 'G-QLEX9V8QQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDymtJGLQsyRFmCXvKmqzH0qKNDjJo5LlU',
    appId: '1:144488728010:android:f6aa78e6c9cbb2a463bb33',
    messagingSenderId: '144488728010',
    projectId: 'najiztest',
    storageBucket: 'najiztest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmYYnbwvRJ0WrpZsemTOK54c7LaNgUcww',
    appId: '1:144488728010:ios:7efede759d36194a63bb33',
    messagingSenderId: '144488728010',
    projectId: 'najiztest',
    storageBucket: 'najiztest.appspot.com',
    iosClientId: '144488728010-kn510acu5vlk3cacuc3i305qss1d58q8.apps.googleusercontent.com',
    iosBundleId: 'com.najizFlutter.app',
  );
}
